---
name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  rubygems:
    if: github.repository == 'jorgemanrubia/truncato'
    runs-on: ubuntu-24.04

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: development:test:benchmark

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - uses: rubygems/release-gem@v1

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
