---
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rspec:
    name: ruby-${{ matrix.ruby }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"

    env:
      BUNDLE_WITHOUT: development:benchmark

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: |
          bundle exec rspec --force-color --format documentation
